name: teleprompter
description: Flutter package to create a teleprompter from a text, record and save to gallery feature
version: 0.1.1
homepage: https://incaview.com
repository: https://github.com/ivofernandes/teleprompter

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_colorpicker: ^1.0.3
  gal: ^2.3.0
  logger: ^2.0.2+1
  top_snackbar_flutter: ^3.1.0
  native_device_orientation: ^2.0.3
  stop_watch_timer: ^3.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  # No changes in this section
